# Generated by Django 5.1.4 on 2025-06-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_baseuser_is_first_login'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('last_generated_at', models.DateTimeField(auto_now=True)),
                ('last_conversation_count', models.IntegerField(default=0)),
                ('last_message_timestamp', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_cache', to='accounts.student')),
            ],
        ),
    ]
