# Generated by Django 5.1.4 on 2025-06-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_baseuser_is_first_login'),
        ('vocab_trainer', '0014_alter_textbook_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_cost', models.PositiveIntegerField(default=0)),
                ('japanese_translation', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('textbook', '教科書準拠'), ('eiken', '英検対策')], default='textbook', max_length=20)),
                ('eiken_level', models.CharField(blank=True, choices=[('5', '英検5級'), ('4', '英検4級'), ('3', '英検3級'), ('pre2', '英検準2級'), ('2', '英検2級')], max_length=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student')),
                ('used_contexts', models.ManyToManyField(blank=True, to='vocab_trainer.wordmeaningcontext')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField()),
                ('batch_id', models.PositiveIntegerField(default=1)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='listening_trainer.listeningpassage')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_answers', to='accounts.student')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='listening_trainer.listeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentListeningPassageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_priority', models.FloatField(default=1.0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening_trainer.listeningpassage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'passage')},
            },
        ),
    ]
