# Generated by Django 5.1.4 on 2025-06-28 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening_trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlisteningpassageprogress',
            name='review_priority',
        ),
        migrations.AddField(
            model_name='studentlisteningpassageprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='studentlisteningpassageprogress',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentlisteningpassageprogress',
            name='next_due_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentlisteningpassageprogress',
            name='repetition_count',
            field=models.IntegerField(default=0),
        ),
    ]
