# Generated by Django 5.1.4 on 2025-07-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening_trainer', '0002_remove_studentlisteningpassageprogress_review_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningpassage',
            name='used_contexts',
        ),
    ]
