# Generated by Django 5.1.4 on 2025-10-17 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_baseuser_is_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=64, verbose_name='Channel ID')),
                ('bot_user_id', models.CharField(db_index=True, help_text='webhookのdestinationに入るbotユーザーID（例: Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx）', max_length=34, validators=[django.core.validators.RegexValidator(regex='^U[0-9a-f]{32}$')], verbose_name='BotユーザーID')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_channels', to='accounts.organization', verbose_name='所属組織')),
            ],
        ),
        migrations.CreateModel(
            name='LineChannelKeyBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CHANNEL_SECRET', 'Channel Secret'), ('ACCESS_TOKEN', 'Channel Access Token')], db_index=True, max_length=32, verbose_name='鍵種別')),
                ('secret_ciphertext', models.BinaryField(verbose_name='暗号文')),
                ('secret_nonce', models.BinaryField(verbose_name='ノンス')),
                ('secret_wrapped_dek', models.BinaryField(verbose_name='ラップ済みDEK')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_bundles', to='line_channels.linechannel', verbose_name='チャンネル')),
            ],
        ),
        migrations.AddIndex(
            model_name='linechannel',
            index=models.Index(fields=['organization', 'bot_user_id'], name='line_channe_organiz_425715_idx'),
        ),
        migrations.AddIndex(
            model_name='linechannel',
            index=models.Index(fields=['organization', 'channel_id'], name='line_channe_organiz_75714e_idx'),
        ),
        migrations.AddConstraint(
            model_name='linechannel',
            constraint=models.UniqueConstraint(fields=('organization', 'bot_user_id'), name='uq_org_bot_user_id'),
        ),
        migrations.AddConstraint(
            model_name='linechannel',
            constraint=models.UniqueConstraint(fields=('organization', 'channel_id'), name='uq_org_channel_id'),
        ),
        migrations.AddIndex(
            model_name='linechannelkeybundle',
            index=models.Index(fields=['line_channel', 'kind', 'is_active'], name='line_channe_line_ch_a7f00f_idx'),
        ),
        migrations.AddConstraint(
            model_name='linechannelkeybundle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('line_channel', 'kind'), name='uq_active_keybundle_per_kind'),
        ),
    ]
