# Generated by Django 5.1.3 on 2026-01-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linechannel',
            options={'permissions': [('manage_line_channels', 'Can manage LINE channels (create/update/rotate secrets)'), ('view_line_channel_secret_metadata', 'Can view LINE channel secret metadata (not values)')]},
        ),
    ]
