# Generated by Django 5.1.4 on 2025-06-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicalWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_form', models.CharField(max_length=50)),
                ('reading', models.CharField(max_length=50)),
                ('part_of_speech', models.CharField(choices=[('noun', '名詞'), ('verb', '動詞'), ('adj', '形容詞'), ('adv', '副詞'), ('conj', '接続詞'), ('prt', '助詞'), ('aux', '助動詞')], max_length=20)),
                ('has_inflection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=20)),
                ('form_value', models.CharField(max_length=50)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflections', to='kobun_trainer.classicalword')),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='kobun_trainer.classicalword')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classical_text', models.TextField()),
                ('modern_translation', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='kobun_trainer.meaning')),
            ],
        ),
    ]
