# Generated by Django 5.1.4 on 2025-01-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', '月曜日'), ('tuesday', '火曜日'), ('wednesday', '水曜日'), ('thursday', '木曜日'), ('friday', '金曜日'), ('saturday', '土曜日'), ('sunday', '日曜日')], help_text='通知する曜日（例: 月曜日、火曜日）。', max_length=10)),
                ('time_of_day', models.TimeField(help_text='通知の時間を24時間形式で設定します（例: 14:30）。')),
                ('is_active', models.BooleanField(default=True, help_text='このリマインダーが現在有効であるかを示します。')),
                ('custom_message', models.CharField(blank=True, help_text='通知メッセージを任意に設定できます。未設定の場合、ChatGPTが生成したメッセージが使用されます。', max_length=200, null=True)),
                ('last_notified', models.DateField(blank=True, help_text='このリマインダーが最後に通知された日付を記録します。重複通知を防止します。', null=True)),
                ('student', models.ForeignKey(help_text='このリマインダーが関連付けられている学生', on_delete=django.db.models.deletion.CASCADE, related_name='study_reminders', to='accounts.student')),
            ],
        ),
    ]
