# Generated by Django 5.1.4 on 2025-01-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyreminder',
            options={'ordering': ['day_of_week', 'time_of_day']},
        ),
    ]
