# Generated by Django 5.1.4 on 2025-03-14 09:31

import study_reminder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_reminder', '0002_alter_studyreminder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyreminder',
            options={},
        ),
        migrations.AlterField(
            model_name='studyreminder',
            name='time_of_day',
            field=models.TimeField(help_text='通知の時間を15分間隔の24時間形式で設定します（例: 15:15, 14:30）。', validators=[study_reminder.models.validate_time_in_15_min_intervals]),
        ),
    ]
