# Generated by Django 5.1.3 on 2026-05-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_reminder', '0003_alter_studyreminder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyreminder',
            name='learning_link_destination',
            field=models.CharField(blank=True, choices=[('', 'リンクなし'), ('student_home', '生徒ホーム')], default='', help_text='通知メッセージに追加する学習リンク', max_length=50, verbose_name='学習リンク'),
        ),
    ]
