# Generated by Django 5.1.3 on 2026-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_reminder', '0004_studyreminder_learning_link_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyreminder',
            name='learning_link_destination',
            field=models.CharField(blank=True, choices=[('', 'リンクなし'), ('student_home', '生徒ホーム'), ('read_textbook', 'リーディング・教科書'), ('read_eiken', 'リーディング・英検'), ('listening_textbook', 'リスニング・教科書'), ('listening_eiken', 'リスニング・英検')], default='', help_text='通知メッセージに追加する学習リンク', max_length=50, verbose_name='学習リンク'),
        ),
    ]
