# Generated by Django 5.1.4 on 2025-01-14 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='メールアドレス')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='名前')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ権限')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='スーパーユーザー権限')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('role', models.CharField(choices=[('student', '生徒'), ('teacher', '講師'), ('classroom_admin', '教室管理者'), ('organization_admin', '組織管理者')], max_length=50, verbose_name='役割')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='組織名')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='教室名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='accounts.organization', verbose_name='所属組織')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAdministrator',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='administrators', to='accounts.classroom', verbose_name='担当教室')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='OrganizationAdministrator',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organizations', models.ManyToManyField(blank=True, related_name='administrators', to='accounts.organization', verbose_name='担当組織')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='teachers', to='accounts.classroom', verbose_name='担当教室')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('line_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='LINEユーザーID')),
                ('classrooms', models.ManyToManyField(blank=True, related_name='students', to='accounts.classroom', verbose_name='所属教室')),
                ('teachers', models.ManyToManyField(blank=True, related_name='students', to='accounts.teacher', verbose_name='担当講師')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
    ]
