# Generated by Django 5.1.4 on 2025-01-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('student', '生徒'), ('teacher', '講師'), ('classroom_administrator', '教室管理者'), ('organization_administrator', '組織管理者')], max_length=50, verbose_name='役割'),
        ),
    ]
