# Generated by Django 5.1.4 on 2025-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(0, '未就学児'), (1, '小学1年生'), (2, '小学2年生'), (3, '小学3年生'), (4, '小学4年生'), (5, '小学5年生'), (6, '小学6年生'), (7, '中学1年生'), (8, '中学2年生'), (9, '中学3年生'), (10, '高校1年生'), (11, '高校2年生'), (12, '高校3年生'), (13, '浪人生'), (14, '社会人')], null=True, verbose_name='学年'),
        ),
    ]
