# Generated by Django 5.1.4 on 2025-02-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomadministrator',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='administrators', to='accounts.classroom', verbose_name='管理教室'),
        ),
        migrations.AlterField(
            model_name='organizationadministrator',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='administrators', to='accounts.organization', verbose_name='管理組織'),
        ),
    ]
