# Generated by Django 5.1.4 on 2025-02-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_classroomadministrator_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(related_name='teachers', to='accounts.classroom', verbose_name='担当教室'),
        ),
    ]
