# Generated by Django 5.1.4 on 2025-03-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacher_classrooms'),
        ('vocab_trainer', '0012_contextpartofspeech'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='textbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab_trainer.textbook', verbose_name='使用教科書'),
        ),
    ]
