# Generated by Django 5.1.4 on 2025-06-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_first_login',
            field=models.BooleanField(default=True, verbose_name='初回ログインフラグ'),
        ),
    ]
