# Generated by Django 5.1.4 on 2025-11-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_baseuser_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.organization', verbose_name='所属組織'),
        ),
    ]
