# Generated by Django 5.1.4 on 2025-11-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_student_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_administrators', to='accounts.organization', verbose_name='所属組織'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='accounts.organization', verbose_name='所属組織'),
        ),
    ]
