# Generated by Django 5.1.3 on 2026-02-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_classroomadministrator_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('assign_organization_administrator', 'Can assign user to organization administrator')]},
        ),
    ]
