# Generated by Django 5.1.3 on 2026-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='last_send_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='send_status',
            field=models.CharField(choices=[('pending', '未送信'), ('sent', '送信成功'), ('failed', '送信失敗')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
