# Generated by Django 5.1.3 on 2026-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_invitation_last_send_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('assign_organization_administrator', 'Can assign user to organization administrator'), ('view_all_organizations', 'Can view all organizations')]},
        ),
        migrations.AlterModelOptions(
            name='organizationadministrator',
            options={'permissions': [('view_all_organization_administrators', 'Can view all organization administrators')]},
        ),
    ]
