# Generated by Django 5.1.3 on 2026-03-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('assign_organization_administrator', 'Can assign user to organization administrator'), ('view_all_organizations', 'Can view all organizations'), ('invite_organization_administrator', 'Invite new organization administrator')]},
        ),
    ]
