# Generated by Django 5.1.3 on 2026-06-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_studentemailregistrationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.organization', verbose_name='所属組織'),
        ),
    ]
