# Generated by Django 5.1.3 on 2026-06-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_student_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomadministrator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_administrators', to='accounts.organization', verbose_name='所属組織'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='accounts.organization', verbose_name='所属組織'),
        ),
    ]
