# Generated by Django 5.1.3 on 2026-07-26 08:16

from django.db import migrations, models


def create_default_gate_row(apps, schema_editor):
    """
    通常状態はOFFという要件を満たすため、モデル作成直後にis_enabled=Falseの
    シングルトン行を作成しておく。行がなければis_currently_enabled()は
    安全側(=True)を返すため、この初期データ投入がないと通常運用が
    ゲートに阻まれてしまう。
    """
    OrganizationAdminInvitationGate = apps.get_model('accounts', 'OrganizationAdminInvitationGate')
    OrganizationAdminInvitationGate.objects.using(schema_editor.connection.alias).get_or_create(
        pk=1,
        defaults={'is_enabled': False},
    )


def noop_reverse(apps, schema_editor):
    # CreateModelのreverse(DeleteModel)で行ごと消えるため、ここでは何もしない
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_classroomadministrator_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAdminInvitationGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='ゲート有効')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '組織管理者招待ゲート',
                'verbose_name_plural': '組織管理者招待ゲート',
            },
        ),
        migrations.RunPython(create_default_gate_row, noop_reverse),
    ]
