# Generated by Django 5.1.3 on 2026-07-27 11:33

from django.db import migrations


def delete_stale_permissions(apps, schema_editor):
    """
    Djangoのcreate_permissions(post_migrateシグナル)は不足分の権限を
    追加するのみで、Meta.permissionsから除かれた権限を自動削除しない。
    そのため、AlterModelOptionsだけでは古いPermission行がauth_permission
    テーブルに孤立データとして残り続ける。ここで明示的に削除する。

    Note:
        post_migrateシグナル(ContentType/Permissionの作成)は、対象の
        migrate実行に含まれる全migration適用後にまとめて1回だけ発火する。
        フレッシュDBからの初回migrate実行では、本migrationが実行される
        時点でaccountsアプリのContentTypeがまだ存在しないため、
        ContentType.objects.get()は使わずfilter().first()で存在しない
        場合を許容する(その場合はPermission自体も存在し得ないため、
        削除対象なしとして無害にスキップする)。
    """
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    organization_ct = ContentType.objects.using(db_alias).filter(
        app_label='accounts', model='organization',
    ).first()
    if organization_ct is not None:
        Permission.objects.using(db_alias).filter(
            content_type=organization_ct,
            codename='assign_organization_administrator',
        ).delete()

    org_admin_ct = ContentType.objects.using(db_alias).filter(
        app_label='accounts', model='organizationadministrator',
    ).first()
    if org_admin_ct is not None:
        Permission.objects.using(db_alias).filter(
            content_type=org_admin_ct,
            codename='view_all_organization_administrators',
        ).delete()


def recreate_stale_permissions(apps, schema_editor):
    """delete_stale_permissionsのreverse。行を再作成する(削除前の
    Group/User割当までは復元しない。復元が必要な場合は別途対応する)。"""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    organization_ct = ContentType.objects.using(db_alias).filter(
        app_label='accounts', model='organization',
    ).first()
    if organization_ct is not None:
        Permission.objects.using(db_alias).get_or_create(
            content_type=organization_ct,
            codename='assign_organization_administrator',
            defaults={'name': 'Can assign user to organization administrator'},
        )

    org_admin_ct = ContentType.objects.using(db_alias).filter(
        app_label='accounts', model='organizationadministrator',
    ).first()
    if org_admin_ct is not None:
        Permission.objects.using(db_alias).get_or_create(
            content_type=org_admin_ct,
            codename='view_all_organization_administrators',
            defaults={'name': 'Can view all organization administrators'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_organizationadmininvitationgate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('view_all_organizations', 'Can view all organizations'), ('invite_organization_administrator', 'Invite new organization administrator')]},
        ),
        migrations.AlterModelOptions(
            name='organizationadministrator',
            options={},
        ),
        migrations.RunPython(delete_stale_permissions, reverse_code=recreate_stale_permissions),
    ]
