# Generated by Django 5.1.3 on 2026-07-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_bulk_assign_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_administrators', to='accounts.organization', verbose_name='所属組織'),
        ),
    ]
