# Generated by Django 5.1.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_backfill_organizationadministrator_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadministrator',
            name='organization',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.PROTECT, related_name='fk_administrators', to='accounts.organization', verbose_name='所属組織'),
        ),
    ]
