# Generated by Django 5.1.3 on 2026-08-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_organizationadministrator_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationadministrator',
            name='organizations',
        ),
        migrations.AlterField(
            model_name='organizationadministrator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrators', to='accounts.organization', verbose_name='所属組織'),
        ),
    ]
