# Generated by Django 5.1.3 on 2026-08-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_organizationadministrator_organizations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationAdminInvitationGate',
        ),
    ]
