# Generated by Django 5.1.3 on 2026-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_organizationadmininvitationgate'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='baseuser',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False)), name='ck_baseuser_is_superuser_always_false'),
        ),
    ]
