# Generated by Django 5.1.4 on 2025-02-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_teacher_classrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50, unique=True)),
                ('name_jp', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('name_jp', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('atomic_number', models.PositiveIntegerField(unique=True)),
                ('category', models.CharField(choices=[('alkali', 'アルカリ金属'), ('halogen', 'ハロゲン'), ('noble_gas', '希ガス'), ('other', 'その他')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.CharField(max_length=255, unique=True)),
                ('level', models.CharField(choices=[('junior_high', '中学'), ('senior_high', '高校'), ('university', '大学')], default='junior_high', max_length=20)),
                ('products', models.ManyToManyField(related_name='product_in', to='chem_trainer.compound')),
                ('reactants', models.ManyToManyField(related_name='reactant_in', to='chem_trainer.compound')),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chemical_equation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='chem_trainer.chemicalequation')),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='elements',
            field=models.ManyToManyField(related_name='compounds', to='chem_trainer.element'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('chemical_equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='chem_trainer.chemicalequation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_progress', to='accounts.student')),
            ],
        ),
    ]
