# Generated by Django 5.1.4 on 2025-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalequation',
            name='latex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='latex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='latex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
