# Generated by Django 5.1.4 on 2025-03-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_trainer', '0002_chemicalequation_latex_compound_latex_element_latex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalequation',
            name='level',
        ),
        migrations.AlterField(
            model_name='chemicalequation',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_in', to='chem_trainer.compound'),
        ),
        migrations.AlterField(
            model_name='chemicalequation',
            name='reactants',
            field=models.ManyToManyField(blank=True, related_name='reactant_in', to='chem_trainer.compound'),
        ),
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.CharField(choices=[('alkali_metal', 'アルカリ金属'), ('alkaline_earth_metal', 'アルカリ土類金属'), ('halogen', 'ハロゲン'), ('noble_gas', '貴ガス'), ('other_metal', 'その他の金属元素'), ('other_nonmetal', 'その他の非金属元素'), ('transition_metal', '遷移元素')], max_length=50),
        ),
        migrations.CreateModel(
            name='ElementalSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50, unique=True)),
                ('name_jp', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('latex', models.CharField(blank=True, max_length=100, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='chem_trainer.element')),
            ],
        ),
    ]
