# Generated by Django 5.1.4 on 2025-03-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_trainer', '0003_remove_chemicalequation_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalequation',
            name='products',
        ),
        migrations.RemoveField(
            model_name='chemicalequation',
            name='reactants',
        ),
        migrations.AddField(
            model_name='chemicalequation',
            name='product_compounds',
            field=models.ManyToManyField(blank=True, related_name='product_compound_in', to='chem_trainer.compound'),
        ),
        migrations.AddField(
            model_name='chemicalequation',
            name='product_substances',
            field=models.ManyToManyField(blank=True, related_name='product_in', to='chem_trainer.elementalsubstance'),
        ),
        migrations.AddField(
            model_name='chemicalequation',
            name='reactant_compounds',
            field=models.ManyToManyField(blank=True, related_name='reactant_compound_in', to='chem_trainer.compound'),
        ),
        migrations.AddField(
            model_name='chemicalequation',
            name='reactant_substances',
            field=models.ManyToManyField(blank=True, related_name='reactant_in', to='chem_trainer.elementalsubstance'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='compounds', to='chem_trainer.element'),
        ),
    ]
