# Generated by Django 5.1.4 on 2025-03-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacher_classrooms'),
        ('chem_trainer', '0004_remove_chemicalequation_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='chemical_equation',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='student',
        ),
        migrations.CreateModel(
            name='CompoundDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('compound', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='chem_trainer.compound')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='chem_trainer.element')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquationDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('chemical_equation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='chem_trainer.chemicalequation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCompoundProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('review_priority', models.FloatField(default=1.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='chem_trainer.compound')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_progress', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentElementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('review_priority', models.FloatField(default=1.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='chem_trainer.element')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_progress', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEquationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('review_priority', models.FloatField(default=1.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('chemical_equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='chem_trainer.chemicalequation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equation_progress', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSubstanceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('review_priority', models.FloatField(default=1.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_progress', to='accounts.student')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='chem_trainer.elementalsubstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubstanceDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('substance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='chem_trainer.elementalsubstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
