# Generated by Django 5.1.4 on 2025-03-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_trainer', '0005_remove_studentprogress_chemical_equation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compounddifficulty',
            name='compound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compound_difficulty', to='chem_trainer.compound'),
        ),
        migrations.AlterField(
            model_name='elementdifficulty',
            name='element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='element_difficulty', to='chem_trainer.element'),
        ),
        migrations.AlterField(
            model_name='equationdifficulty',
            name='chemical_equation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equation_difficulty', to='chem_trainer.chemicalequation'),
        ),
        migrations.AlterField(
            model_name='substancedifficulty',
            name='substance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='substance_difficulty', to='chem_trainer.elementalsubstance'),
        ),
    ]
