"""
Django settings for django_study_hub project.

Generated by 'django-admin startproject' using Django 5.1.3.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 先に .env を読む
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env", override=False)
except Exception:
    pass

# Windows ローカルでは gRPC を無効化して REST にフォールバック
if os.name == "nt" and os.getenv("ENV", "local") == "local":
    os.environ.setdefault("GOOGLE_CLOUD_DISABLE_GRPC", "true")


def _get_from_secret(secret_name: str) -> str | None:
    try:
        from google.cloud import secretmanager

        project_id = (
            os.getenv("GCP_PROJECT")
            or os.getenv("GOOGLE_CLOUD_PROJECT")
            or os.getenv("GCP_PROJECT_ID_FALLBACK", "your-gcp-project-id")
        )
        name = f"projects/{project_id}/secrets/{secret_name}/versions/latest"
        client = secretmanager.SecretManagerServiceClient()
        resp = client.access_secret_version(name=name)
        return resp.payload.data.decode("utf-8")
    except Exception:
        return None


def _must_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise EnvironmentError(f"環境変数 '{name}' が設定されていません。")
    return value


def _must(secret_name: str, env_name: str | None = None) -> str:
    value = (os.getenv(env_name) if env_name else None) or _get_from_secret(secret_name)
    if not value:
        raise RuntimeError(
            f"Secret '{secret_name}' が取得できません（env '{env_name}' も無し）"
        )
    return value


# 環境切り替え
ENV = os.getenv("ENV", "local")

# 共通設定
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
CSRF_TRUSTED_ORIGINS = []
MEDIA_URL = "/media/"

# 公開用に実値は持たせない
LINE_KMS_KEY_RESOURCE = os.getenv("LINE_KMS_KEY_RESOURCE")

# 公開URL / 表示用設定
APP_NAME = os.getenv("APP_NAME", "StudyHub")
APP_PUBLIC_BASE_URL_PROD = os.getenv(
    "APP_PUBLIC_BASE_URL_PROD",
    "https://your-app.example.com",
)

# メール送信元設定
EMAIL_NOREPLY_ADDRESS = os.getenv("EMAIL_NOREPLY_ADDRESS", "noreply@example.com")
EMAIL_CONTACT_ADDRESS = os.getenv("EMAIL_CONTACT_ADDRESS", "contact@example.com")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", EMAIL_NOREPLY_ADDRESS)
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = f"{APP_NAME} <{EMAIL_NOREPLY_ADDRESS}>"
DEFAULT_FROM_EMAIL_ADDRESS = EMAIL_NOREPLY_ADDRESS
DEFAULT_REPLY_TO_EMAIL_ADDRESS = EMAIL_CONTACT_ADDRESS
DEFAULT_SUPPORT_EMAIL_ADDRESS = EMAIL_CONTACT_ADDRESS

if ENV == "local":
    print("Running in LOCAL environment")

    SECRET_KEY = _must_env("DJANGO_SECRET_KEY")
    DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    ALLOWED_HOSTS += [".ngrok-free.app"]
    CSRF_TRUSTED_ORIGINS += [
        "https://*.ngrok-free.app",
    ]

    LINE_CHANNEL_SECRET = _must_env("LINE_CHANNEL_SECRET")
    LINE_CHANNEL_ACCESS_TOKEN = _must_env("LINE_CHANNEL_ACCESS_TOKEN")
    OPENAI_API_KEY = _must_env("OPENAI_API_KEY")

    GOOGLE_APPLICATION_CREDENTIALS = _must_env("GOOGLE_APPLICATION_CREDENTIALS")
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS

    DATABASE_PASSWORD = _must_env("DATABASE_PASSWORD")
    LOCAL_DB_NAME = os.getenv("LOCAL_DB_NAME", "my-local-db")
    LOCAL_DB_USER = os.getenv("LOCAL_DB_USER", "db-user")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": LOCAL_DB_NAME,
            "USER": LOCAL_DB_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "HOST": "127.0.0.1",
            "PORT": "5432",
        }
    }

    TEACHER_DEFAULT_PASSWORD = _must_env("TEACHER_DEFAULT_PASSWORD")
    STUDENT_DEFAULT_PASSWORD = _must_env("STUDENT_DEFAULT_PASSWORD")

    MEDIA_ROOT = BASE_DIR / "media"
    PUBSUB_REMINDER_TOPIC = os.getenv("PUBSUB_REMINDER_TOPIC", "reminder-topic-dev")
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend"
    )

else:
    print("Running in PRODUCTION environment")

    SECRET_KEY = _must("django-secret-key", "DJANGO_SECRET_KEY")
    LINE_CHANNEL_SECRET = _must("line_channel_secret", "LINE_CHANNEL_SECRET")
    LINE_CHANNEL_ACCESS_TOKEN = _must("line_channel_access_token", "LINE_CHANNEL_ACCESS_TOKEN")
    OPENAI_API_KEY = _must("openai-api-key", "OPENAI_API_KEY")
    DJANGO_DB_PASSWORD = _must("db-password", "DJANGO_DB_PASSWORD")

    DEBUG = False
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    ALLOWED_HOSTS = [
        host.strip()
        for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
        if host.strip()
    ]

    if APP_PUBLIC_BASE_URL_PROD:
        CSRF_TRUSTED_ORIGINS += [APP_PUBLIC_BASE_URL_PROD]

    GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
    if GOOGLE_APPLICATION_CREDENTIALS:
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS

    DATABASES = {
        "default": {
            "ENGINE": os.getenv("DJANGO_DB_ENGINE"),
            "NAME": os.getenv("DJANGO_DB_NAME"),
            "USER": os.getenv("DJANGO_DB_USER"),
            "PASSWORD": DJANGO_DB_PASSWORD,
            "HOST": os.getenv("DJANGO_DB_HOST"),
            "PORT": os.getenv("DJANGO_DB_PORT"),
        }
    }

    TEACHER_DEFAULT_PASSWORD = os.getenv("TEACHER_DEFAULT_PASSWORD", "changeme")
    STUDENT_DEFAULT_PASSWORD = os.getenv("STUDENT_DEFAULT_PASSWORD", "changeme")

    MEDIA_ROOT = "/tmp/media"
    PUBSUB_REMINDER_TOPIC = os.getenv("PUBSUB_REMINDER_TOPIC", "reminder-topic")
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',  # アカウント管理用(apps.pyを明治)
    'conversations',  # 会話ログ管理用に追加
    'line_integration',  # Line API 応答用アプリ
    'study_reminder', # リマインダー機能管理
    'vocab_trainer',  # 英単語学習
    'chem_trainer',  # 化学式学習(ある程度動かせるラインにはあるが、利用していない)
    'read_trainer',  # 長文練習
    'kobun_trainer',  # 古文単語学習(最低限の構成のみで、まだ稼働していない)
    'audio_support',  # 音声を用いた学習のサポート
    'listening_trainer',  # リスニング問題
    'math_trainer',  # 数学問題
    'text_scheduler',  # 教材管理
    'line_channels',  # LINEチャネル管理アプリ（KMSによるエンベロープ暗号化でシークレットを管理）
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_study_hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.homepage_url',  # ユーザごとのホームページを規定
                'accounts.context_processors.unassigned_students_count',  # 未割り当て生徒を通知するためのプロセッサー
                'accounts.context_processors.debug_mode',  # ローカルか本番環境かを本番で検知するためのプロセッサー
                'audio_support.context_processors.media_url',  # 音声ファイルの保存先を示す
            ],
        },
    },
]

WSGI_APPLICATION = 'django_study_hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# env, localのところで設定済み


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 収集された静的ファイルの保存先

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# カスタムユーザーモデルを設定し、認証処理などで利用するようにする
AUTH_USER_MODEL = 'accounts.BaseUser'

#HSTSの設定(HTTPS通信を強制)
if DEBUG:
    SECURE_HSTS_SECONDS = 0  # ローカル環境ではHSTSを無効化
else:
    SECURE_HSTS_SECONDS = 31536000  # HSTSを1年間（単位:秒）有効化
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # サブドメインもHSTS対象にする
SECURE_HSTS_PRELOAD = True  # HSTS Preloadリストに登録する（後述）

# XSSフィルターの設定 (スクリプトを埋め込み、不正な動作を実行)
SECURE_BROWSER_XSS_FILTER = True
# MIMEタイプのスニッフィング防止(ブラウザのコンテンツ推測の悪用)
SECURE_CONTENT_TYPE_NOSNIFF = True
# クリックジャッキング対策(透明なフレームでクリック先を誤認させる)
X_FRAME_OPTIONS = 'DENY'

# ログインに利用するURL
LOGIN_URL = '/accounts/auth/login/'
# ログイン後のリダイレクト先(現在はリマインダー編集画面)
# LOGIN_REDIRECT_URL = '/study_reminder/manage/' 
# ログアウト後のリダイレクト先(現在はログイン画面)
LOGOUT_REDIRECT_URL = '/accounts/auth/login/'

# ヘッダーを見て、HTTPSを判断する
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# listener.pyやcloud_functions/main.pyを除いて内部で利用するログの統一設定
LOG_LEVEL = "DEBUG" if ENV == "local" else "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        # Django のリクエスト周り
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # 必要に応じて apps 別ロガーを追加してもOK
        # "accounts": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
    },
}

GCP_PROJECT_ID_FALLBACK = os.getenv("GCP_PROJECT_ID_FALLBACK", "your-gcp-project-id")
PUBSUB_SUBSCRIPTION = os.getenv("PUBSUB_SUBSCRIPTION", "your-subscription-name")
OIDC_AUDIENCE = APP_PUBLIC_BASE_URL_PROD

APP_PUBLIC_BASE_URL_PROD = os.getenv(
    "APP_PUBLIC_BASE_URL_PROD",
    "https://your-app.example.com",
)

# メール送信設定（ローカル/プロダクション共通）
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = True

# OpenAI モデル設定（環境変数で上書き可能）
OPENAI_MODEL_CHAT = os.getenv("OPENAI_MODEL_CHAT", "gpt-4o")
OPENAI_MODEL_SHORT_TASK = os.getenv("OPENAI_MODEL_SHORT_TASK", "gpt-4")
OPENAI_MODEL_SUMMARY = os.getenv("OPENAI_MODEL_SUMMARY", "gpt-4o")
OPENAI_MODEL_PASSAGE_GENERATION = os.getenv("OPENAI_MODEL_PASSAGE_GENERATION", "gpt-4o")
