# Generated by Django 5.1.4 on 2025-09-29 13:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_baseuser_is_first_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('unit_label', models.CharField(default='番', max_length=32)),
                ('start_number', models.PositiveIntegerField()),
                ('end_number', models.PositiveIntegerField()),
                ('required_reviews', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('estimated_minutes_per_unit', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('goal_date', models.DateField(blank=True, null=True)),
                ('buffer_weekdays', models.JSONField(blank=True, default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_materials', to=settings.AUTH_USER_MODEL)),
                ('target_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('suggested_new_count', models.PositiveSmallIntegerField(default=0)),
                ('suggested_review_numbers', models.JSONField(default=list)),
                ('estimated_total_minutes', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_sched_daily_plans', to='accounts.student')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='text_scheduler.learningmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'new'), ('learning', 'learning'), ('reviewing', 'reviewing'), ('mastered', 'mastered')], default='new', max_length=12)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('repetition_count', models.PositiveIntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('total_spent_minutes', models.PositiveIntegerField(default=0)),
                ('last_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('sum_quality', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progress', to='text_scheduler.learningmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_sched_progress', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('studied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('initial', 'initial'), ('review', 'review')], max_length=7)),
                ('quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('point_1', models.CharField(blank=True, default='', max_length=300)),
                ('point_2', models.CharField(blank=True, default='', max_length=300)),
                ('point_3', models.CharField(blank=True, default='', max_length=300)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('spent_minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)])),
                ('source', models.CharField(default='ui', max_length=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='text_scheduler.learningmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_sched_logs', to='accounts.student')),
            ],
            options={
                'ordering': ['-studied_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='learningmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('end_number__gte', models.F('start_number'))), name='material_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='learningmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', False), ('goal_date__isnull', False), ('goal_date__gt', models.F('start_date'))), name='material_start_and_goal_required_strict_order'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('student', 'material', 'date')},
        ),
        migrations.AddIndex(
            model_name='studentunitprogress',
            index=models.Index(fields=['student', 'material', 'number'], name='text_schedu_student_799b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentunitprogress',
            index=models.Index(fields=['student', 'material', 'next_due_at'], name='text_schedu_student_98240c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentunitprogress',
            unique_together={('student', 'material', 'number')},
        ),
        migrations.AddIndex(
            model_name='studylog',
            index=models.Index(fields=['student', 'material', 'number'], name='text_schedu_student_5a7888_idx'),
        ),
        migrations.AddIndex(
            model_name='studylog',
            index=models.Index(fields=['student', 'material', 'studied_at'], name='text_schedu_student_58abea_idx'),
        ),
        migrations.AddConstraint(
            model_name='studylog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quality__gte', 0), ('quality__lte', 5)), ('quality__isnull', True), _connector='OR'), name='log_quality_range_0_5_or_null'),
        ),
        migrations.AddConstraint(
            model_name='studylog',
            constraint=models.CheckConstraint(condition=models.Q(('spent_minutes__gte', 0), ('spent_minutes__lte', 240)), name='log_spent_minutes_0_240'),
        ),
        migrations.AddConstraint(
            model_name='studylog',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['initial', 'review'])), name='log_kind_valid'),
        ),
    ]
