# Generated by Django 5.1.4 on 2025-10-03 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='suggested_review_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='buffer_weekdays',
            field=models.JSONField(blank=True, default=list, verbose_name='予備日'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='end_number',
            field=models.PositiveIntegerField(verbose_name='終了番号'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='estimated_minutes_per_unit',
            field=models.PositiveSmallIntegerField(default=5, help_text='1単位を終えるために必要だと予測される時間', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='1単位あたりの推定時間'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='goal_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='達成済みか否か'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='required_reviews',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='必要復習回数'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='start_number',
            field=models.PositiveIntegerField(verbose_name='開始番号'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='教材名'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='unit_label',
            field=models.CharField(default='番', help_text='問,ページ,番など', max_length=32, verbose_name='学習単位'),
        ),
    ]
