# Generated by Django 5.1.4 on 2025-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_scheduler', '0002_alter_dailyplan_suggested_review_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='is_correct',
            field=models.CharField(choices=[('true', '正解'), ('false', '不正解'), ('unknown', '不明')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='kind',
            field=models.CharField(choices=[('initial', '初回学習'), ('review', '復習')], max_length=7),
        ),
    ]
