# Generated by Django 5.1.4 on 2025-10-11 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_scheduler', '0003_alter_studylog_is_correct_alter_studylog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='daily_minutes_budget',
            field=models.PositiveIntegerField(default=45, help_text='この教材に1日あたり費やせる時間(分)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='estimated_minutes_per_unit',
            field=models.PositiveSmallIntegerField(default=5, help_text='1単位を終えるために必要だと予測される時間(分)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='1単位あたりの推定時間'),
        ),
    ]
