# Generated by Django 5.1.4 on 2025-12-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_scheduler', '0004_learningmaterial_daily_minutes_budget_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learningmaterial',
            name='material_range_valid',
        ),
        migrations.RemoveConstraint(
            model_name='learningmaterial',
            name='material_start_and_goal_required_strict_order',
        ),
    ]
