# Generated by Django 5.1.4 on 2025-08-06 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_baseuser_is_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='問題タイプ名')),
                ('grade', models.IntegerField(blank=True, choices=[(0, '未就学児'), (1, '小学1年生'), (2, '小学2年生'), (3, '小学3年生'), (4, '小学4年生'), (5, '小学5年生'), (6, '小学6年生'), (7, '中学1年生'), (8, '中学2年生'), (9, '中学3年生'), (10, '高校1年生'), (11, '高校2年生'), (12, '高校3年生')], null=True, verbose_name='対象学年')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'grade'), name='unique_problemtype_name_grade')],
            },
        ),
        migrations.CreateModel(
            name='ProblemSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('display', 'Display'), ('print', 'Print')], max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_trainer.problemtype')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.CharField(max_length=200)),
                ('choice_texts', models.JSONField(help_text='選択肢のリスト（answerを含む）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='math_trainer.problemsession')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_trainer.problemtype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('problem_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_trainer.probleminstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProblemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempt', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('repetition_count', models.PositiveIntegerField(default=0)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_due_at', models.DateField(blank=True, null=True)),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_trainer.problemtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'problem_type')},
            },
        ),
    ]
