# Generated by Django 5.1.4 on 2025-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probleminstance',
            options={'ordering': ['session', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
