# Generated by Django 5.1.4 on 2025-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_baseuser_is_first_login'),
        ('math_trainer', '0002_alter_probleminstance_options_probleminstance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminstance',
            name='correct_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('student', 'problem_instance'), name='uniq_student_problem_instance'),
        ),
    ]
