# Generated by Django 5.1.4 on 2025-02-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordMeaningRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.CharField(blank=True, choices=[('verb', '動詞'), ('noun', '名詞'), ('adjective', '形容詞'), ('adverb', '副詞'), ('other', 'その他')], max_length=20, null=True)),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='vocab_trainer.englishword')),
                ('japanese_meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_words', to='vocab_trainer.japanesemeaning')),
            ],
        ),
    ]
