# Generated by Django 5.1.4 on 2025-02-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0002_quizresult_worddifficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMeaningRelationDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('difficulty', models.FloatField(default=1.0)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='vocab_trainer.wordmeaningrelation')),
            ],
        ),
        migrations.DeleteModel(
            name='WordDifficulty',
        ),
    ]
