# Generated by Django 5.1.4 on 2025-02-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacher_classrooms'),
        ('vocab_trainer', '0003_wordmeaningrelationdifficulty_delete_worddifficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='word',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='vocab_trainer.wordmeaningrelation'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='accounts.student'),
        ),
    ]
