# Generated by Django 5.1.4 on 2025-02-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0004_remove_quizresult_word_quizresult_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='vocab_trainer.wordmeaningrelation'),
        ),
    ]
