# Generated by Django 5.1.4 on 2025-02-22 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacher_classrooms'),
        ('vocab_trainer', '0005_alter_quizresult_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('review_priority', models.FloatField(default=1.0)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='vocab_trainer.wordmeaningrelation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to='accounts.student')),
            ],
        ),
    ]
