# Generated by Django 5.1.4 on 2025-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0006_studentwordprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmeaningrelation',
            name='part_of_speech',
            field=models.CharField(choices=[('verb', '動詞'), ('noun', '名詞'), ('adjective', '形容詞'), ('adverb', '副詞'), ('other', 'その他')], max_length=20),
        ),
    ]
