# Generated by Django 5.1.4 on 2025-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0007_alter_wordmeaningrelation_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwordprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='studentwordprogress',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
