# Generated by Django 5.1.4 on 2025-02-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0008_studentwordprogress_ease_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('publisher', models.CharField(max_length=100)),
                ('grade', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='vocab_trainer.textbook')),
            ],
        ),
        migrations.CreateModel(
            name='WordAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab_trainer.chapter')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='vocab_trainer.wordmeaningrelation')),
            ],
        ),
    ]
