# Generated by Django 5.1.4 on 2025-03-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0009_textbook_chapter_wordappearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='wordmeaningrelation',
            name='part_of_speech',
        ),
        migrations.CreateModel(
            name='WordMeaningContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meaning_contexts', to='vocab_trainer.chapter')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='vocab_trainer.wordmeaningrelation')),
            ],
        ),
        migrations.AddField(
            model_name='quizresult',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='vocab_trainer.wordmeaningcontext'),
        ),
        migrations.CreateModel(
            name='WordMeaningRelationPartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_trainer.partofspeech')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_of_speech', to='vocab_trainer.wordmeaningrelation')),
            ],
            options={
                'unique_together': {('relation', 'part_of_speech')},
            },
        ),
        migrations.DeleteModel(
            name='WordAppearance',
        ),
    ]
