# Generated by Django 5.1.4 on 2025-03-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacher_classrooms'),
        ('vocab_trainer', '0010_partofspeech_remove_quizresult_relation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContextProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('review_priority', models.FloatField(default=1.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='vocab_trainer.wordmeaningcontext')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_progress', to='accounts.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentWordProgress',
        ),
    ]
