# Generated by Django 5.1.4 on 2025-03-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0011_studentcontextprogress_delete_studentwordprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextPartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of_speeches', to='vocab_trainer.wordmeaningcontext')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_trainer.partofspeech')),
            ],
            options={
                'unique_together': {('context', 'part_of_speech')},
            },
        ),
    ]
