# Generated by Django 5.1.4 on 2025-03-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0012_contextpartofspeech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='textbook',
            unique_together={('name', 'grade')},
        ),
    ]
