# Generated by Django 5.1.4 on 2025-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0013_alter_textbook_name_alter_textbook_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textbook',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='textbook',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='textbook',
            unique_together={('name', 'grade', 'publication_year')},
        ),
    ]
