# Generated by Django 5.1.4 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0014_alter_textbook_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontextprogress',
            name='last_is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcontextprogress',
            name='next_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcontextprogress',
            name='repetition_count',
            field=models.IntegerField(default=0),
        ),
    ]
