# Generated by Django 5.1.3 on 2026-05-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_trainer', '0015_studentcontextprogress_last_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='vocab_trainer.textbook'),
        ),
    ]
