# Generated by Django 5.1.4 on 2025-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='batch_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
