# Generated by Django 5.1.4 on 2025-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_trainer', '0002_readingquestion_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpassage',
            name='japanese_translation',
            field=models.TextField(blank=True),
        ),
    ]
