# Generated by Django 5.1.4 on 2025-05-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_textbook'),
        ('read_trainer', '0003_readingpassage_japanese_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReadingPassageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_priority', models.FloatField(default=1.0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_trainer.readingpassage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'passage')},
            },
        ),
    ]
