# Generated by Django 5.1.4 on 2025-05-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_trainer', '0004_studentreadingpassageprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpassage',
            name='eiken_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='source_type',
            field=models.CharField(choices=[('textbook', '教科書準拠'), ('eiken', '英検対策')], default='textbook', max_length=20),
        ),
    ]
