# Generated by Django 5.1.4 on 2025-06-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_trainer', '0005_readingpassage_eiken_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingpassage',
            name='eiken_level',
            field=models.CharField(blank=True, choices=[('5', '英検5級'), ('4', '英検4級'), ('3', '英検3級'), ('pre2', '英検準2級'), ('2', '英検2級')], max_length=5, null=True),
        ),
    ]
