# Generated by Django 5.1.4 on 2025-07-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_trainer', '0006_alter_readingpassage_eiken_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingpassage',
            name='used_contexts',
        ),
    ]
