# Generated by Django 5.1.4 on 2025-07-18 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_trainer', '0007_remove_readingpassage_used_contexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreadingpassageprogress',
            name='review_priority',
        ),
        migrations.AddField(
            model_name='studentreadingpassageprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='studentreadingpassageprogress',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentreadingpassageprogress',
            name='next_due_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentreadingpassageprogress',
            name='repetition_count',
            field=models.IntegerField(default=0),
        ),
    ]
